#!/usr/bin/env python3
"""Deterministic scenario-model generator for JSE research.

Builds the styled multi-tab Excel scenario model (Cover, Macro Deck, per-company
Actuals + Scenario Model, shared Assumptions, optional Resilience Scorecard) from
version-controlled inputs:

  assumptions/<slug>.json   per-company anchor (sacred actuals) + scenario drivers
  macro/latest.json         shared, dated macro context + scenario macro levels
  comparisons/<name>.json   (optional) scorecard + verdict for a multi-company run

The financial logic lives in Excel FORMULAS (not hardcoded), so the workbook stays
live: change a blue input on the Assumptions tab and every figure recomputes. This
replaces the ad-hoc one-off build scripts - the structure and house style are now
written and tested once. Mirrors tools/manifest.py's deterministic discipline.

Usage:
  python3 tools/build_model.py shoprite --out model.xlsx
  python3 tools/build_model.py shoprite spar --scorecard comparisons/shoprite-vs-spar.json \\
      --title "Shoprite vs The SPAR Group - Hormuz Scenario Model" --out compare.xlsx

Templates supported: retail-owned (e.g. Shoprite), retail-wholesale (e.g. SPAR).
"""
import argparse
import glob
import json
import os
import subprocess
import sys

from openpyxl import Workbook
from openpyxl.utils import get_column_letter

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import report_style as rs

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FMT = {"num": rs.FMT_NUM, "num1": rs.FMT_NUM1, "pct": rs.FMT_PCT,
       "pct2": rs.FMT_PCT2, "mult": rs.FMT_MULT, "cent": rs.FMT_CENT,
       "ratio": rs.FMT_RATIO}


def load_json(path):
    with open(path) as f:
        return json.load(f)


def flatten_columns(scenarios):
    """Return ordered list of (label, key, year, scen_idx, year_idx) data columns."""
    cols = []
    for si, sc in enumerate(scenarios):
        for yi, year in enumerate(sc["years"].keys()):
            short = sc["key"]
            cols.append((f"{short} {year}", sc["key"], year, si, yi))
    return cols


def col_letters(n_data):
    """Anchor in column C (index 3); data columns follow."""
    return [get_column_letter(3 + i) for i in range(n_data + 1)]  # +1 for anchor


def prior_letter(letters, data_idx, scen_idx, year_idx, cols):
    """Excel column letter of the prior period for a given data column."""
    if year_idx == 0:
        return letters[0]  # anchor column C
    # previous year within the same scenario = the data column immediately before
    return letters[data_idx]  # data_idx is 1-based offset (anchor=0), so prev is this-1... handled by caller


# ----------------------------------------------------------------- sheet: Cover
def build_cover(wb, companies, macro, title, subtitle):
    ws = wb.active
    ws.title = "Cover"
    ws.sheet_view.showGridLines = False
    rs.xl_title_block(ws, title, subtitle, span=8)
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 42
    for c in "CDEFGH":
        ws.column_dimensions[c].width = 15
    r = 4
    blocks = [
        ("HOW TO USE THIS MODEL", "h"),
        ("Change only the BLUE cells on the Assumptions tab. BLACK cells are formulas; GREEN cells link across sheets. Each scenario runs for two forward years against the FY anchor.", "p"),
        ("Generated by tools/build_model.py from assumptions/<slug>.json + macro/latest.json. Do not hand-edit; re-run the generator.", "p"),
        ("", ""),
        ("METHODOLOGY", "h"),
        ("retail-owned: Sale of merchandise = prior x (1 + selling-price inflation + real volume/space). Trading profit = sales x trading margin. Earnings (e) = trading profit - net finance - tax, over a calibrated effective share count so the FY anchor HEPS ties to the reported figure.", "p"),
        ("retail-wholesale: Turnover = prior x (1 + growth). Gross & operating profit = turnover x margin. Continuing HEPS (e) is modelled directly off the actual prints (the reported bridge carries large extraordinary/discontinued items); net debt, leverage and finance costs are modelled explicitly because de-gearing is the equity thesis.", "p"),
        ("", ""),
        ("FY ANCHORS (reported actuals - sacred)", "h"),
    ]
    for text, kind in blocks:
        c = ws.cell(r, 2, text)
        if kind == "h":
            rs.xl_cell(c, bold=True, size=11, color=rs.NAVY)
        elif kind == "p":
            rs.xl_cell(c, size=9, wrap=True)
            ws.row_dimensions[r].height = 34
        ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=8)
        r += 1
    # anchor mini-table
    for comp in companies:
        a = comp["anchor"]
        rs.xl_cell(ws.cell(r, 2, f"{comp['name']} ({comp['jse_code']})  -  {comp['anchor_label']}"),
                   bold=True, size=10, color=rs.WHITE,
                   fill=(rs.ACCENT if comp["template"] == "retail-owned" else rs.ACCENT2))
        ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=8)
        r += 1
        for label, key, fmt in comp["_anchor_display"]:
            rs.xl_cell(ws.cell(r, 2, label), size=9, bold=True, fill=rs.LTGREY, border=True)
            v = a.get(key)
            rs.xl_cell(ws.cell(r, 3, v), size=9, border=True, align="center", fmt=FMT.get(fmt))
            ws.merge_cells(start_row=r, start_column=3, end_row=r, end_column=4)
            rs.xl_cell(ws.cell(r, 5, a.get("source", "")), size=8, italic=True, wrap=True, border=True)
            ws.merge_cells(start_row=r, start_column=5, end_row=r, end_column=8)
            r += 1
        r += 1
    rs.xl_cell(ws.cell(r, 2, "DISCLAIMER"), bold=True, size=11, color=rs.NAVY)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=8); r += 1
    rs.xl_cell(ws.cell(r, 2, rs.SACRED_NOTE + " " + rs.DISCLAIMER), size=8, italic=True, wrap=True)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=8)
    ws.row_dimensions[r].height = 60


# ----------------------------------------------------------------- sheet: Macro Deck
def build_macro(wb, macro):
    ws = wb.create_sheet("Macro Deck")
    ws.sheet_view.showGridLines = False
    rs.xl_title_block(ws, macro["title"] + f"  (as at {macro['as_at']})",
                      macro["sources_note"], span=4)
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 34
    ws.column_dimensions["C"].width = 32
    ws.column_dimensions["D"].width = 40
    r = 4
    last_section = None
    for row in macro["rows"]:
        if row["section"] != last_section:
            rs.xl_cell(ws.cell(r, 2, row["section"]), bold=True, size=11, color=rs.WHITE, fill=rs.ACCENT)
            ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
            r += 1
            last_section = row["section"]
        rs.xl_cell(ws.cell(r, 2, row["metric"]), size=9, bold=True, fill=rs.LTGREY, border=True)
        rs.xl_cell(ws.cell(r, 3, row["value"]), size=9, border=True)
        rs.xl_cell(ws.cell(r, 4, row["source"]), size=9, italic=True, border=True)
        r += 1
    r += 1
    rs.xl_cell(ws.cell(r, 2, "Why it matters: " + macro["why_it_matters"]),
               size=8, italic=True, wrap=True, fill=rs.YELLOW)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
    ws.row_dimensions[r].height = 70


# ----------------------------------------------------------------- sheet: Actuals
def build_actuals(wb, comp):
    ws = wb.create_sheet(f"{comp['jse_code']} Actuals")
    ws.sheet_view.showGridLines = False
    fill = rs.ACCENT if comp["template"] == "retail-owned" else rs.ACCENT2
    rs.xl_title_block(ws, f"{comp['name']} - FY ANCHOR (reported actuals)",
                      "SACRED - do not edit. Source on Cover. Drives the scenario model.", span=4)
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 44
    ws.column_dimensions["C"].width = 18
    ws.column_dimensions["D"].width = 40
    r = 4
    rs.xl_cell(ws.cell(r, 2, "Metric"), bold=True, color=rs.WHITE, fill=fill, border=True)
    rs.xl_cell(ws.cell(r, 3, comp["anchor_label"]), bold=True, color=rs.WHITE, fill=fill, border=True, align="center")
    rs.xl_cell(ws.cell(r, 4, "Note"), bold=True, color=rs.WHITE, fill=fill, border=True)
    r += 1
    a = comp["anchor"]
    for label, key, fmt in comp["_anchor_display"]:
        rs.xl_cell(ws.cell(r, 2, label), size=9, bold=True, fill=rs.LTGREY, border=True)
        rs.xl_cell(ws.cell(r, 3, a.get(key)), size=9, align="center", border=True, fmt=FMT.get(fmt))
        rs.xl_cell(ws.cell(r, 4, "(e)" if "(e)" in str(key) else ""), size=8, italic=True, border=True)
        r += 1
    r += 1
    rs.xl_cell(ws.cell(r, 2, a.get("source", "")), size=8, italic=True, wrap=True, fill=rs.YELLOW)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=4)
    ws.row_dimensions[r].height = 40


# ----------------------------------------------------------------- sheet: Assumptions
DRIVER_SPECS = {
    "retail-owned": [
        ("infl", "Internal selling-price inflation (%)", "pct"),
        ("vol", "Real volume + space growth (%)", "pct"),
        ("gross_margin", "Gross margin (%)", "pct"),
        ("trading_margin", "Trading margin (%)", "pct"),
        ("net_finance_costs_rm", "Net finance costs (R'm)", "num"),
    ],
    "retail-wholesale": [
        ("turnover_growth", "Turnover growth (%)", "pct"),
        ("gross_margin", "Gross margin (%)", "pct"),
        ("op_margin", "Operating margin, ex-extraordinary (%)", "pct"),
        ("net_finance_costs_rm", "Net finance costs (R'm) (e)", "num"),
        ("heps_c", "Continuing HEPS (e), cents - anchored on actuals", "cent"),
        ("net_debt_rm", "Net debt (R'm)", "num"),
        ("leverage_x", "Net debt leverage (x)", "mult"),
        ("dps_c", "DPS (e), cents", "cent"),
    ],
}
ANCHOR_KEY = {  # which anchor field seeds the FY2025A column for each driver
    "infl": None, "vol": None, "gross_margin": "gross_margin",
    "trading_margin": "trading_margin", "net_finance_costs_rm": "net_finance_costs_rm",
    "turnover_growth": None, "op_margin": "op_margin", "heps_c": "heps_actual_c",
    "net_debt_rm": "net_debt_rm", "leverage_x": "leverage_x", "dps_c": "dps_c",
}


def build_assumptions(wb, companies, macro, letters):
    ws = wb.create_sheet("Assumptions")
    ws.sheet_view.showGridLines = False
    rs.xl_title_block(ws, "SCENARIO ASSUMPTIONS",
                      "BLUE = input you can change. Forward figures are analyst estimates (e); macro levels are assumptions, not forecasts.")
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 44
    for L in letters:
        ws.column_dimensions[L].width = 12
    reg = {}  # (slug, driver_key) -> row ; also ("macro", name) -> row

    def header(r, comp=None):
        labels = ["FY2025A"] + [c[0] for c in companies[0]["_cols"]] if comp is None else None
        # build header from the shared column layout
        rs.xl_cell(ws.cell(r, 2, ""), border=True)
        rs.xl_cell(ws.cell(r, 3, companies[0]["anchor_label"]), bold=True, size=9,
                   color=rs.WHITE, fill=rs.MIDGREY, align="center", border=True)
        for j, (label, key, year, si, yi) in enumerate(companies[0]["_cols"]):
            rs.xl_cell(ws.cell(r, 4 + j, label), bold=True, size=9, color=rs.WHITE,
                       fill=rs.scenario_palette(key), align="center", wrap=True, border=True)
        ws.row_dimensions[r].height = 26

    r = 4
    # macro block
    rs.xl_cell(ws.cell(r, 2, "SHARED MACRO (analyst scenario assumptions - see Macro Deck)"),
               bold=True, size=11, color=rs.WHITE, fill=rs.NAVY)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=2); r += 1
    header(r); r += 1
    for name, spec in macro["scenario_levels"].items():
        fmt = FMT.get(spec.get("fmt", "num"))
        rs.xl_cell(ws.cell(r, 2, name), size=9, bold=True, fill=rs.LTGREY, border=True)
        rs.xl_cell(ws.cell(r, 3, spec["FY2025A"]), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=fmt)
        for j, (label, key, year, si, yi) in enumerate(companies[0]["_cols"]):
            val = spec[key][yi]
            rs.xl_cell(ws.cell(r, 4 + j, val), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=fmt)
        r += 1
    r += 1
    # per-company driver blocks
    for comp in companies:
        fill = rs.ACCENT if comp["template"] == "retail-owned" else rs.ACCENT2
        rs.xl_cell(ws.cell(r, 2, f"{comp['name']} ({comp['jse_code']}) - drivers"),
                   bold=True, size=11, color=rs.WHITE, fill=fill)
        ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=2); r += 1
        header(r); r += 1
        a = comp["anchor"]
        for key, label, fmt in DRIVER_SPECS[comp["template"]]:
            rs.xl_cell(ws.cell(r, 2, label), size=9, bold=True, fill=rs.LTGREY, border=True)
            anchor_field = ANCHOR_KEY.get(key)
            anchor_val = a.get(anchor_field) if anchor_field else None
            rs.xl_cell(ws.cell(r, 3, anchor_val), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=FMT.get(fmt))
            for j, (clabel, ckey, year, si, yi) in enumerate(comp["_cols"]):
                yv = comp["scenarios"][si]["years"][year].get(key)
                rs.xl_cell(ws.cell(r, 4 + j, yv), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=FMT.get(fmt))
            reg[(comp["slug"], key)] = r
            r += 1
        # constants needed by formulas (owned template)
        if comp["template"] == "retail-owned":
            for key, label, fmt, val in [
                ("tax_rate", "Effective tax rate (%)", "pct", a["tax_rate"]),
                ("div_cover", "Dividend cover (x)", "mult", a["div_cover"]),
                ("group_rev_ratio", "Group rev / sale-of-merch ratio (x)", "ratio", a["group_rev_ratio"]),
                ("eff_diluted_shares_m", "Effective diluted shares (m)", "num1", a["eff_diluted_shares_m"]),
            ]:
                rs.xl_cell(ws.cell(r, 2, label), size=9, bold=True, fill=rs.LTGREY, border=True)
                for cc in range(3, 3 + 1 + len(comp["_cols"])):
                    rs.xl_cell(ws.cell(r, cc, val), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=FMT.get(fmt))
                reg[(comp["slug"], key)] = r
                r += 1
        else:
            rs.xl_cell(ws.cell(r, 2, "Shares in issue (m) - calibrated (e)"), size=9, bold=True, fill=rs.LTGREY, border=True)
            for cc in range(3, 3 + 1 + len(comp["_cols"])):
                rs.xl_cell(ws.cell(r, cc, a["shares_m"]), size=9, color=rs.INPUT_BLUE, align="center", border=True, fmt=FMT.get("num"))
            reg[(comp["slug"], "shares_m")] = r
            r += 1
        if comp.get("rationale"):
            rs.xl_cell(ws.cell(r, 2, comp["rationale"]), size=8, italic=True, wrap=True, fill=rs.YELLOW)
            ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=2 + len(comp["_cols"]) + 1)
            ws.row_dimensions[r].height = 74
            r += 1
        r += 1
    return reg


def aref(slug, key, col, reg):
    return f"Assumptions!${col}${reg[(slug, key)]}"


# ----------------------------------------------------------------- sheet: Scenario Model
def build_scenario_model(wb, comp, letters, reg):
    ws = wb.create_sheet(f"{comp['jse_code']} Scenario Model")
    ws.sheet_view.showGridLines = False
    fill = rs.ACCENT if comp["template"] == "retail-owned" else rs.ACCENT2
    rs.xl_title_block(ws, f"{comp['name']} - SCENARIO MODEL",
                      "BLACK = formula; GREEN = link to Assumptions. (e) = analyst estimate. FY anchor reproduces reported actuals.")
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 40
    for L in letters:
        ws.column_dimensions[L].width = 13
    # header
    r = 4
    rs.xl_cell(ws.cell(r, 2, "R'm unless stated"), bold=True, size=9, color=rs.WHITE, fill=rs.NAVY, border=True)
    rs.xl_cell(ws.cell(r, 3, comp["anchor_label"]), bold=True, size=9, color=rs.WHITE, fill=rs.MIDGREY, align="center", border=True)
    for j, (label, key, year, si, yi) in enumerate(comp["_cols"]):
        rs.xl_cell(ws.cell(r, 4 + j, label), bold=True, size=9, color=rs.WHITE, fill=rs.scenario_palette(key), align="center", wrap=True, border=True)
    ws.row_dimensions[r].height = 26
    r += 1
    slug = comp["slug"]
    cols = comp["_cols"]
    datacols = letters[1:]  # exclude anchor col

    def prior_col_for(j):
        si, yi = cols[j][3], cols[j][4]
        if yi == 0:
            return letters[0]
        # previous year same scenario = previous data column
        return datacols[j - 1]

    def line(label, bold=False):
        rs.xl_cell(ws.cell(r, 2, label), size=9, bold=bold, border=True, fill=(rs.LTGREY if bold else None))

    rows = {}
    if comp["template"] == "retail-owned":
        # Sale of merchandise
        line("Sale of merchandise", True); rows["sale"] = r
        rs.xl_cell(ws.cell(r, 3, comp["anchor"]["sale_of_merchandise_rm"]), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        for j, L in enumerate(datacols):
            pc = prior_col_for(j)
            ws.cell(r, 4 + j).value = f"={pc}{rows['sale']}*(1+{aref(slug,'infl',L,reg)}+{aref(slug,'vol',L,reg)})"
            rs.xl_cell(ws.cell(r, 4 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("Group revenue (e)"); rows["rev"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['sale']}*{aref(slug,'group_rev_ratio',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("Gross profit"); rows["gp"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['sale']}*{aref(slug,'gross_margin',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("  Gross margin (%)")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['gp']}/{L}{rows['sale']}"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True)
        r += 1
        line("Trading profit", True); rows["tp"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['sale']}*{aref(slug,'trading_margin',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, bold=True)
        r += 1
        line("  Trading margin (%)")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['tp']}/{L}{rows['sale']}"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True)
        r += 1
        line("less: Net finance costs"); rows["nfc"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"=-{aref(slug,'net_finance_costs_rm',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, color=rs.LINK_GREEN)
        r += 1
        line("Profit before tax - proxy (e)"); rows["pbt"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['tp']}+{L}{rows['nfc']}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("less: Tax (e)"); rows["tax"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"=-{L}{rows['pbt']}*{aref(slug,'tax_rate',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("Earnings - proxy (e)", True); rows["ear"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['pbt']}+{L}{rows['tax']}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, bold=True)
        r += 1
        line("Diluted HEPS - proxy (e), cents", True); rows["heps"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['ear']}/{aref(slug,'eff_diluted_shares_m',L,reg)}*100"
            rs.xl_cell(ws.cell(r, 3 + j), size=10, fmt=rs.FMT_CENT, align="center", border=True, bold=True, fill=rs.LTGREY)
        r += 1
        line("  HEPS growth (%)")
        for j, L in enumerate(letters):
            if j == 0:
                rs.xl_cell(ws.cell(r, 3, "-"), size=8, align="center", italic=True, border=True); continue
            pc = prior_col_for(j - 1)
            ws.cell(r, 3 + j).value = f"={L}{rows['heps']}/{pc}{rows['heps']}-1"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True)
        r += 1
        line("DPS - total (e), cents")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['heps']}/{aref(slug,'div_cover',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_CENT, align="center", border=True)
        r += 1
    else:  # retail-wholesale
        line("Turnover (continuing)", True); rows["to"] = r
        rs.xl_cell(ws.cell(r, 3, comp["anchor"]["turnover_rm"]), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        for j, L in enumerate(datacols):
            pc = prior_col_for(j)
            ws.cell(r, 4 + j).value = f"={pc}{rows['to']}*(1+{aref(slug,'turnover_growth',L,reg)})"
            rs.xl_cell(ws.cell(r, 4 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("  Turnover growth (%)")
        for j, L in enumerate(letters):
            if j == 0:
                rs.xl_cell(ws.cell(r, 3, "-"), size=8, align="center", italic=True, border=True); continue
            pc = prior_col_for(j - 1)
            ws.cell(r, 3 + j).value = f"={L}{rows['to']}/{pc}{rows['to']}-1"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True)
        r += 1
        line("Gross profit"); rows["gp"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['to']}*{aref(slug,'gross_margin',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True)
        r += 1
        line("Operating profit (ex-extraordinary)", True); rows["op"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['to']}*{aref(slug,'op_margin',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, bold=True)
        r += 1
        line("  Operating margin (%)")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={aref(slug,'op_margin',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True, color=rs.LINK_GREEN)
        r += 1
        line("less: Net finance costs (e)")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"=-{aref(slug,'net_finance_costs_rm',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, color=rs.LINK_GREEN)
        r += 1
        line("Continuing HEPS (e), cents", True); rows["heps"] = r
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={aref(slug,'heps_c',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=10, fmt=rs.FMT_CENT, align="center", border=True, bold=True, fill=rs.LTGREY, color=rs.LINK_GREEN)
        r += 1
        line("  HEPS growth (%)")
        for j, L in enumerate(letters):
            if j == 0:
                rs.xl_cell(ws.cell(r, 3, "-"), size=8, align="center", italic=True, border=True); continue
            pc = prior_col_for(j - 1)
            ws.cell(r, 3 + j).value = f"={L}{rows['heps']}/{pc}{rows['heps']}-1"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_PCT, align="center", italic=True, border=True)
        r += 1
        line("  Implied cont. headline earnings (memo)")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={L}{rows['heps']}*{aref(slug,'shares_m',L,reg)}/100"
            rs.xl_cell(ws.cell(r, 3 + j), size=8, fmt=rs.FMT_NUM, align="center", italic=True, border=True)
        r += 1
        line("Net debt");
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={aref(slug,'net_debt_rm',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_NUM, align="center", border=True, color=rs.LINK_GREEN)
        r += 1
        line("  Net debt leverage (x)", True)
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={aref(slug,'leverage_x',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_MULT, align="center", border=True, color=rs.LINK_GREEN, bold=True)
        r += 1
        line("DPS (e), cents")
        for j, L in enumerate(letters):
            ws.cell(r, 3 + j).value = f"={aref(slug,'dps_c',L,reg)}"
            rs.xl_cell(ws.cell(r, 3 + j), size=9, fmt=rs.FMT_CENT, align="center", border=True, color=rs.LINK_GREEN)
        r += 1


# ----------------------------------------------------------------- sheet: Scorecard
def build_scorecard(wb, spec):
    ws = wb.create_sheet("Resilience Scorecard")
    ws.sheet_view.showGridLines = False
    rs.xl_title_block(ws, spec["title"], spec["subtitle"], span=6)
    ws.column_dimensions["A"].width = 3
    ws.column_dimensions["B"].width = 30
    ws.column_dimensions["C"].width = 9
    ws.column_dimensions["D"].width = 9
    ws.column_dimensions["E"].width = 39
    ws.column_dimensions["F"].width = 39
    a_code, b_code = spec["companies"]
    r = 4
    for j, h in enumerate(["Dimension", a_code, b_code, f"Why {a_code}", f"Why {b_code}"]):
        fill = rs.NAVY
        if h == a_code:
            fill = rs.ACCENT
        elif h == b_code:
            fill = rs.ACCENT2
        rs.xl_cell(ws.cell(r, 2 + j, h), bold=True, size=10, color=rs.WHITE, fill=fill, align="center", wrap=True, border=True)
    ws.row_dimensions[r].height = 20
    first = r + 1
    r += 1
    for row in spec["rows"]:
        rs.xl_cell(ws.cell(r, 2, row["dimension"]), size=9, bold=True, fill=rs.LTGREY, wrap=True, border=True)
        rs.xl_cell(ws.cell(r, 3, row["a"]), size=11, bold=True, align="center", color=rs.WHITE, fill=rs.score_fill(row["a"]), border=True)
        rs.xl_cell(ws.cell(r, 4, row["b"]), size=11, bold=True, align="center", color=rs.WHITE, fill=rs.score_fill(row["b"]), border=True)
        rs.xl_cell(ws.cell(r, 5, row["why_a"]), size=8, wrap=True, border=True)
        rs.xl_cell(ws.cell(r, 6, row["why_b"]), size=8, wrap=True, border=True)
        ws.row_dimensions[r].height = 30
        r += 1
    last = r - 1
    rs.xl_cell(ws.cell(r, 2, "AVERAGE SCORE"), size=10, bold=True, color=rs.WHITE, fill=rs.NAVY, border=True)
    ws.cell(r, 3).value = f"=AVERAGE(C{first}:C{last})"
    rs.xl_cell(ws.cell(r, 3), size=12, bold=True, align="center", color=rs.WHITE, fill=rs.ACCENT, fmt="0.0", border=True)
    ws.cell(r, 4).value = f"=AVERAGE(D{first}:D{last})"
    rs.xl_cell(ws.cell(r, 4), size=12, bold=True, align="center", color=rs.WHITE, fill=rs.ACCENT2, fmt="0.0", border=True)
    rs.xl_cell(ws.cell(r, 5, spec.get("avg_note_a", "")), size=9, italic=True, wrap=True, border=True)
    rs.xl_cell(ws.cell(r, 6, spec.get("avg_note_b", "")), size=9, italic=True, wrap=True, border=True)
    ws.row_dimensions[r].height = 24
    r += 2
    rs.xl_cell(ws.cell(r, 2, "VERDICT"), bold=True, size=12, color=rs.WHITE, fill=rs.NAVY)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=6); r += 1
    rs.xl_cell(ws.cell(r, 2, spec["verdict"]), size=10, wrap=True, fill=rs.YELLOW, border=True)
    ws.merge_cells(start_row=r, start_column=2, end_row=r, end_column=6)
    ws.row_dimensions[r].height = 140


# ----------------------------------------------------------------- recalc
def find_recalc():
    cands = []
    if os.environ.get("JSE_XLSX_RECALC"):
        cands.append(os.environ["JSE_XLSX_RECALC"])
    cands += glob.glob("/sessions/*/mnt/.claude/skills/xlsx/scripts/recalc.py")
    cands += glob.glob(os.path.expanduser("~") + "/**/skills/xlsx/scripts/recalc.py", recursive=True)
    for c in cands:
        if os.path.exists(c):
            return c
    return None


def recalc(path):
    script = find_recalc()
    if not script:
        print("WARN: recalc.py not found; skipping recalc. Run tools/verify_deliverable.py separately.", file=sys.stderr)
        return None
    out = subprocess.run([sys.executable, script, path, "60"], capture_output=True, text=True)
    try:
        res = json.loads(out.stdout)
    except json.JSONDecodeError:
        print("WARN: recalc output unparseable:", out.stdout[-300:], file=sys.stderr)
        return None
    return res


# ----------------------------------------------------------------- main
ANCHOR_DISPLAY = {
    "retail-owned": [
        ("Sale of merchandise (R'm)", "sale_of_merchandise_rm", "num"),
        ("Gross margin (%)", "gross_margin", "pct"),
        ("Trading margin (%)", "trading_margin", "pct"),
        ("Net finance costs (R'm)", "net_finance_costs_rm", "num"),
        ("Diluted HEPS (continuing), c", "heps_actual_c", "cent"),
        ("Effective diluted shares (m)", "eff_diluted_shares_m", "num1"),
        ("Dividend cover (x)", "div_cover", "mult"),
    ],
    "retail-wholesale": [
        ("Turnover (R'm)", "turnover_rm", "num"),
        ("Gross margin (%)", "gross_margin", "pct"),
        ("Operating margin ex-extra (%)", "op_margin", "pct"),
        ("Continuing HEPS, c", "heps_actual_c", "cent"),
        ("Net debt (R'm)", "net_debt_rm", "num"),
        ("Net debt leverage (x)", "leverage_x", "mult"),
        ("Shares in issue (m)", "shares_m", "num"),
    ],
}


def main():
    ap = argparse.ArgumentParser(description="Build a JSE scenario model workbook.")
    ap.add_argument("slugs", nargs="+", help="company slug(s), e.g. shoprite spar")
    ap.add_argument("--out", required=True)
    ap.add_argument("--scorecard", help="comparison scorecard JSON (multi-company)")
    ap.add_argument("--title")
    ap.add_argument("--subtitle", default="Investment Committee working model - internal research, for information only")
    ap.add_argument("--no-recalc", action="store_true")
    args = ap.parse_args()

    companies = []
    for slug in args.slugs:
        comp = load_json(os.path.join(ROOT, "assumptions", f"{slug}.json"))
        comp["_cols"] = flatten_columns(comp["scenarios"])
        comp["_anchor_display"] = ANCHOR_DISPLAY[comp["template"]]
        companies.append(comp)
    # all companies must share the same column layout for the shared Assumptions sheet
    base_cols = companies[0]["_cols"]
    for comp in companies[1:]:
        if [c[1:3] for c in comp["_cols"]] != [c[1:3] for c in base_cols]:
            sys.exit("ERROR: companies have mismatched scenario/year layouts; align assumptions files.")
    macro = load_json(os.path.join(ROOT, "macro", "latest.json"))
    letters = col_letters(len(base_cols))

    title = args.title or f"{companies[0]['name']} - Scenario Model"
    wb = Workbook()
    build_cover(wb, companies, macro, title, args.subtitle)
    if companies and len(companies) > 1 and args.scorecard:
        build_scorecard(wb, load_json(args.scorecard if os.path.isabs(args.scorecard) else os.path.join(ROOT, args.scorecard)))
    build_macro(wb, macro)
    for comp in companies:
        build_actuals(wb, comp)
    reg = build_assumptions(wb, companies, macro, letters)
    for comp in companies:
        build_scenario_model(wb, comp, letters, reg)

    out = args.out if os.path.isabs(args.out) else os.path.join(os.getcwd(), args.out)
    wb.save(out)
    print(f"wrote {out}")
    if not args.no_recalc:
        res = recalc(out)
        if res is not None:
            if res.get("total_errors", 0) > 0:
                print("FORMULA ERRORS:", json.dumps(res.get("error_summary", {}), indent=2))
                sys.exit(2)
            print(f"recalc OK: {res.get('total_formulas')} formulas, 0 errors")


if __name__ == "__main__":
    main()
